name: 'Remove Large Ubuntu Packages'
runs:
  using: "composite"
  steps:
    - name: Pkg Cleanup
      id: pkg-cleanup
      shell: bash
      run: |
        df -h
        if [[ $(uname -s) == "Linux" ]]; then
        ubuntu_ver=$(cat /etc/os-release | grep VERSION_ID |cut -d \" -f 2)
        sudo apt-get purge -y azure-cli || true
        sudo apt-get purge -y google-cloud-cli  google-chrome-stable || true
        sudo apt-get purge -y firefox || true
        sudo apt-get purge -y microsoft-edge-stable || true
        sudo apt-get purge -y dotnet-sdk-*
        sudo apt-get purge -y mono-* || true
        sudo apt-get purge -y temurin-*-jdk  openjdk-*
        sudo apt-get purge -y powershell || true
        sudo apt-get purge -y docker-ce containerd.io || true
        sudo apt-get purge -y docker-ce-cli podman kubectl || true
        sudo apt-get purge -y containernetworking-plugins ||true
        sudo apt-get purge -y libclang-common-*dev || true
        sudo apt-get purge -y snapd || true
        sudo apt-get purge -y mysql-client-core* || true
        sudo apt-get purge -y llvm-*-dev
        sudo apt-get purge -y libclang-cpp* libllvm* || true
        sudo apt-get purge -y python3-botocore || true
        sudo apt-get purge -y mongodb-* || true
        sudo apt-get purge -y esl-erlang || true
        sudo apt-get purge -y r-* || true
        sudo apt-get purge gcc-9 || true
        sudo apt-get purge gcc-10 || true
        if [[ $ubuntu_ver == "20.04" ]]; then
           sudo apt-get purge -y hhvm
           sudo apt-get purge -y libgl1-mesa-dri
        fi
        sudo apt-get -y clean
        sudo apt-get autoremove -y
        dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -30
        dpkg-query -l | grep mesa-dr || true
        dpkg-query -l | grep hhvm || true
        df -h
        fi
