name: Example

on:
  schedule:
    - cron: '0 0 * * SUN'
  pull_request:
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:
  workflow_call:       

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v4
        with:
          path: ./.github/actions/ubuntu-pkg-cleanup
      - name: Ubuntu cleanup
        uses: ./.github/actions/ubuntu-pkg-cleanup
  ubuntu-24:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out source
        uses: actions/checkout@v4
        with:
          path: ./.github/actions/ubuntu-pkg-cleanup
      - name: Ubuntu cleanup
        uses: ./.github/actions/ubuntu-pkg-cleanup
  ubuntu-22:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out source
        uses: actions/checkout@v4
        with:
          path: ./.github/actions/ubuntu-pkg-cleanup
      - name: Ubuntu cleanup
        uses: ./.github/actions/ubuntu-pkg-cleanup
  ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out source
        uses: actions/checkout@v4
        with:
          path: ./.github/actions/ubuntu-pkg-cleanup
      - name: Ubuntu cleanup
        uses: ./.github/actions/ubuntu-pkg-cleanup
          
